### PR TITLE
Basic SDM ready

### PR DESCRIPTION
**Pull request by venpopov**
#### Summary

Implemented the simple SDM model via `sdmSimple()`

Currently no default priors or initial values for fit set - I want to think about how to make these general as we discussed in the other issues. I'm marking this pull request as a draft - don't merge it yet, I want to add a few more things on monday.

#### Tests

[X] Confirm that all tests passed
[X] Confirm that devtools::check() produces no errors

#### Release notes

- New model available - The Signal Discrimination Model by Oberauer (2023) for visual working memory continuous reproduction tasks. See `?sdmSimple`. The current version does not take into account non-target activation

### CODE REVIEW

**Comment by venpopov** [comment]
Btw, with the new structure of the package, adding this model via `use_model_template()` was incredibly easy - about 30 minutes of work!

**Comment by venpopov** [comment]
Still to do:
[ ] Default priors
[ ] Initial values for brms
[ ] Document the parametrization (sqrtexp)
[ ] Vignette

**Comment by venpopov** [comment]
It should be ready to go

**Comment by GidonFrischkorn** [comment]
Hi Ven,
I just saw that you already merged the branch into the development branch although I was not finished with my review. I was still in testing an actually ran into an issue comparing rstan and cmdstanr as a backend that I wanted to explore further to make sure there are no bugs with using the model in either backend.
I am not sure, if my review was somehow approved prematurely or if you just decided to verify the pull request yourself.

**Pull request merged**
